version: 1.0.{build}
os: Visual Studio 2015
test: off
clone_folder: C:\projects\robust_hex_dominant_meshing
branches:
  only:
    - master
install:
  - git submodule update --init --recursive
build_script:
  - echo Running cmake...
  - cd c:\projects\robust_hex_dominant_meshing
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#  - set MSBuildOptions=/v:m /p:Configuration=Release /logger:%MSBuildLogger%
  - set MSBuildOptions=/v:m /p:Configuration=Debug /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% robust_hex_dominant_meshing.sln